# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: betterui CI

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # 拉取代码  
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 1、生成静态文件
      - name: Build-Storybook
        run: npm ci && npm run build-storybook

      # 2、部署到 GitHub Pages
      - name: Deploy
        uses: zhuangjiaqing/github-pages-deploy-action@releases/v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: storybook-static
